### ISSUE TITLE
Death by unicode

### ISSUE THREAD

**Issue by aowi** [hartfelt/kiara#5]
I _think_ what happened here, was kiara finishing processing of one directory and moving on to the next. One of them (not sure which) might have had \u200b (zero-width space) in it.

```
Traceback (most recent call last):
  File "/Users/aowi/bin/kiara", line 42, in <module>
    libkiara.process(os.path.abspath(file.name), args.watch, args.organize)
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 92, in process
    print(line)
UnicodeEncodeError: 'ascii' codec can't encode character '\u200b' in position 12: ordinal not in range(128)
aowi@spike ~/ogiue/shit/anime $ Filename in database have changed
----------------------------------------
Exception happened during processing of request from
Traceback (most recent call last):
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 60, in _send
    for i in inner():
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 48, in inner
    client.connect(os.path.expanduser(_config['session']))
socket.error: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/socketserver.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/socketserver.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/socketserver.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/aowi/src/kiara/libkiara/backend.py", line 94, in __init__
    return super().__init__(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/socketserver.py", line 648, in __init__
    self.handle()
  File "/Users/aowi/src/kiara/libkiara/backend.py", line 207, in handle
    self.request.sendall(bytes('---end---', 'UTF-8'))
socket.error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by aowi** [comment]
Got one more, same deal, but in the middle of processing a directory here. They don't repeat, so simply restarting kiara works fine, and it just picks up from where it left off...

```
Hashing [Doki-Shini] Kamisama Dolls - 09v2 (1280x720 h264 AAC) [D5947E55].mkv
Moved /Users/aowi/ogiue/shit/anime/Kamisama Dolls/[Doki-Shini] Kamisama Dolls - 09v2 (1280x720 h264 AAC) [D5947E55].mkv to /Users/aowi/ogiue/shit/anime_series/Kami-sama Dolls/[Doki-Shini] Kami-sama Dolls - 09 [d5947e55].mkv

Traceback (most recent call last):
  File "/Users/aowi/bin/kiara", line 42, in <module>
    libkiara.process(os.path.abspath(file.name), args.watch, args.organize)
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 92, in process
    print(line)
UnicodeEncodeError: 'ascii' codec can't encode character '\xd7' in position 46: ordinal not in range(128)
aowi@spike ~/ogiue/shit/anime $ ----------------------------------------
Exception happened during processing of request from
Traceback (most recent call last):
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 60, in _send
    for i in inner():
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 48, in inner
    client.connect(os.path.expanduser(_config['session']))
socket.error: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/socketserver.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/socketserver.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/socketserver.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/aowi/src/kiara/libkiara/backend.py", line 94, in __init__
    return super().__init__(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/socketserver.py", line 648, in __init__
    self.handle()
  File "/Users/aowi/src/kiara/libkiara/backend.py", line 207, in handle
    self.request.sendall(bytes('---end---', 'UTF-8'))
socket.error: [Errno 32] Broken pipe
----------------------------------------
```
