### ISSUE TITLE
Don't open a million files at once

### ISSUE THREAD

**Issue by aowi** [hartfelt/kiara#6]
It seems that kiara tries to open all the files passed as arguments all at once, causing the error below. I'm guessing a missing close() somewhere.

```
$ kiara -o L*/* K*/*

Unable to contact the backend. Will try to start one...
Traceback (most recent call last):
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 60, in _send
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 47, in inner
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/socket.py", line 94, in __init__
socket.error: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aowi/bin/kiara", line 38, in <module>
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 79, in ping
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 74, in _send
ImportError: cannot import name backend
Traceback (most recent call last):
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 60, in _send
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 47, in inner
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/socket.py", line 94, in __init__
socket.error: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aowi/bin/kiara", line 38, in <module>
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 79, in ping
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 69, in _send
  File "/Users/aowi/src/kiara/libkiara/__init__.py", line 47, in inner
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/socket.py", line 94, in __init__
socket.error: [Errno 24] Too many open files
```

**Comment by hartfelt** [comment]
That's the way argparse handles file arguments... We need to instead accept string arguments, and then check manually if the file exist. (And then open and close it as needed)
